version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    container_name: sofie_app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=sofie
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:5.7
    container_name: sofie_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sofie
    volumes:
      - ./sofie-db-05-04-2016_final.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

volumes:
  db_data: