Sofie\ExpBundle\Entity\Collecte:
    properties:
        nomOperateur:
            - NotBlank: ~
        nomAgentSaisie:
            - NotBlank: ~
        dateSaisie:
            - NotBlank: ~
            - Date: ~
        dateRemplissage:
            - NotBlank: ~
            - Date: ~