Sofie\AdminBundle\Model\ChangePassword:
    properties:
        currentPassword:
            - NotBlank: ~
            - Symfony\Component\Security\Core\Validator\Constraints\UserPassword: ~
        newPassword:
            - NotBlank: ~
            - Length:
                min: 6