Sofie\ExpBundle\Entity\CoupeGeologique:
    exclusion_policy: ALL
    properties:
        coteSup:
            expose: true
            serialized_name: CoteSup
            groups: [api_add]
        coteInf:
            expose: true
            serialized_name: CoteInf
            groups: [api_add]
        lithographie:
            expose: true
            serialized_name: Lithographie
            groups: [api_add]
        description:
            expose: true
            serialized_name: Description
            groups: [api_add]
        sync:
            expose: true
            serialized_name: sync
            groups: [api_add]
        createdAt:
            expose: true
            serialized_name: created_at
            groups: [api_add]
            type: DateTime<'Y-m-d H:i:s'>
        updatedAt:
            expose: true
            serialized_name: updated_at
            groups: [api_add]
            type: DateTime<'Y-m-d H:i:s'>
        position:
            expose: true
            serialized_name: position
            type: integer
            groups: [api_add]