Sofie\ExpBundle\Entity\AppelTelephonique:
    type: entity
    table: t_appeltelephonique
    repositoryClass: Sofie\ExpBundle\Entity\AppelTelephoniqueRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    indexes:
        IDNumAppel:
            columns:
                - IDNumAppel
    id:
        id:
            type: integer
            nullable: false
            id: true
            column: IDAPPEL
            generator:
                strategy: AUTO
    fields:
        dateAppel:
            type: datetime
            nullable: true
            column: DateHeureAppel
        motif:
            type: integer
            nullable: true
            column: MotifAppel
        sync:
            type: string
            length: 1
            nullable: true
            options:
                default: 'N'
            column: sync
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
    manyToOne:
        panne:
            targetEntity: Panne
            cascade: ["persist"]
            inversedBy: appels
            joinColumn:
                name: IDPanne
                nullable: true
                referencedColumnName: IDPanne
                onDelete: "CASCADE"
            orphanRemoval: false
        numeroAppel:
            targetEntity: NumeroAppel
            cascade: ["persist", "remove"]
            inversedBy: appels
            joinColumn:
                name: IDNumAppel
                nullable: true
                referencedColumnName: IDNumAppel
                onDelete: "CASCADE"
            orphanRemoval: false
    lifecycleCallbacks: {  }
