<?php

namespace Sofie\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Sofie\AdminBundle\Model\ParameterFile;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends EntityRepository
{
    public function getNextId()
    {
        return intval($this->createQueryBuilder('c')->select('MAX(c.id)')->getQuery()->getSingleScalarResult())+1;
    }

    public function getCurrent()
    {
        return $this->getCurrentBuilder()->getQuery()->getOneOrNullResult();
    }

    public function getCurrentBuilder()
    {
        $qb = $this->createDefaultBuilder();
        $site = ParameterFile::loadSite();
        $qb->where(
            $qb->expr()->orX(
                $qb->expr()->eq('r.id', ':site'),
                $qb->expr()->andX(
                    $qb->expr()->isNull('r'),
                    $qb->expr()->eq('c.isCentral', ':central')
                )
            )
        )
            ->setParameter('site', intval($site))
            ->setParameter('central', true)
        ;

        return $qb;
    }

    public function getRegionaux()
    {
        return $this->getRegionauxBuilder()->getQuery()->getResult();
    }

    public function getRegionauxBuilder()
    {
        $qb = $this->createDefaultBuilder();
        $qb->where(
            $qb->expr()->isNotNull('r')
        )
        ;

        return $qb;
    }

    protected function createDefaultBuilder()
    {
        $qb = $this->createQueryBuilder('c');
        $qb = $this->myDefaultSelectAll($qb);
//        $qb = $this->myDefaultFilter($qb);
        return $qb;
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb
            ->leftJoin('c.region', 'r')
            ->addSelect('r')
        ;

        return $qb;
    }

    protected function myDefaultOrder(QueryBuilder $qb)
    {
        $qb->orderBy('r.nom', 'ASC')
            ->addOrderBy('c.id', 'ASC')
        ;

        return $qb;
    }

    protected function myDefaultFilter(QueryBuilder $qb)
    {
        /*$site = ParameterFile::loadSite();
        if(!is_null($site)){
            $qb->andWhere($qb->expr()->eq('r.id', ':region'))
                ->setParameter('region', $site)
            ;
        }*/
        return $qb;
    }
}
