<?php

namespace Sofie\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * DelaisNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelaisNotificationRepository extends EntityRepository
{
    public function getLast()
    {
        $last = $this->getEntityManager()->createQuery('SELECT MAX(d.id) FROM SofieAdminBundle:DelaisNotification d')
            ->getSingleScalarResult();

        $last = intval($last);

        $qb = $this->createDefaultBuilder();
        $qb->where($qb->expr()->eq('d.id', ':last'))->setParameter('last', $last);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getAll()
    {
        return $this->createDefaultBuilder()->getQuery()->getResult();
    }

    protected function createDefaultBuilder()
    {
        $qb = $this->createQueryBuilder('d');
        $qb = $this->myDefaultSelectAll($qb);
        return $qb;
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb->leftJoin('d.uniteDelais', 'u')
            ->addSelect('u')
        ;

        return $qb;
    }
}
