<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Sofie\AdminBundle\Entity\Config;
use Sofie\AdminBundle\Model\ParameterFile;
use Sofie\UserBundle\Entity\User;

/**
 * AgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentRepository extends EntityRepository
{
    public function getNextId()
    {
        return intval($this->createQueryBuilder('a')->select('MAX(a.id)')->getQuery()->getSingleScalarResult())+1;
    }

    public function get($id)
    {
        $qb = $this->createDefaultBuilder();
        $qb->andWhere($qb->expr()->eq('a.id', ':id'))->setParameter('id', intval($id));
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getAll($offset = Config::DEFAULT_OFFSET_PAGINATOR, $page = 1)
    {
        return Pagination::renderPagination($this->getAllQuery(), $offset, $page);
    }

    public  function getAllQuery()
    {
        $qb = $this->createDefaultBuilder();
        $qb = $this->criteresNotInAgent($qb);
        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    protected function criteresNotInAgent(QueryBuilder $qb)
    {
        return $qb->andWhere($qb->expr()->notIn('q.id', ':noagent'))->setParameter('noagent', Profile::getNotInAgentListArray());
    }

    public function getTotalByCriteres(array $criteres=array())
    {
        return $this->getCritereQuery($criteres)->getResult();
    }

    public function getByCriteres(array $criteres=array(), $offset=Config::DEFAULT_OFFSET_PAGINATOR, $page=1)
    {
       return Pagination::renderPagination($this->getCritereQuery($criteres), $offset, $page);
    }

    public function getCritereQuery(array $criteres = array())
    {
        $qb = $this->createDefaultBuilder();
        $qb = $this->criteresNotInAgent($qb);

        // Critère région
        if(array_key_exists('region', $criteres)){
            $qb = $this->critereRegion($qb, $criteres['region']);
        }
        // Critère qualification
        if(array_key_exists('qualification', $criteres)){
            $qb = $this->critereQualification($qb, $criteres['qualification']);
        }
        // Critère codeInit
        if(array_key_exists('codeInit', $criteres) && $criteres['codeInit'] != ''){
            $qb = $this->critereCodeInit($qb, $criteres['codeInit']);
        }
        // Critère numeroAppel
        if(array_key_exists('numeroAppel', $criteres) && $criteres['numeroAppel'] != ''){
            $qb = $this->critereNumeroAppel($qb, $criteres['numeroAppel']);
        }
        // Critère nom
        if(array_key_exists('nom', $criteres) && $criteres['nom'] != ''){
            $qb = $this->critereNom($qb, $criteres['nom']);
        }
        // Critère prenoms
        if(array_key_exists('prenoms', $criteres) && $criteres['prenoms'] != ''){
            $qb = $this->criterePrenoms($qb, $criteres['prenoms']);
        }
        // Critère initStatus
        if(array_key_exists('initStatus', $criteres) && $criteres['initStatus'] != ''){
            $qb = $this->critereInitStatus($qb, $criteres['initStatus']);
        }

        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    protected function critereRegion(QueryBuilder $qb, Region $region = null)
    {
        if(!empty($region)){
            $qb->andWhere($qb->expr()->eq('r', ':region'))->setParameter('region', $region);
        }
        return $qb;
    }

    protected function critereQualification(QueryBuilder $qb, Profile $qualification = null)
    {
        if(!empty($qualification)){
            $qb->andWhere($qb->expr()->eq('q', ':qualification'))->setParameter('qualification', $qualification);
        }
        return $qb;
    }

    protected function critereCodeInit(QueryBuilder $qb, $codeInit)
    {
        if($codeInit != ''){
            $qb->andWhere($qb->expr()->like('a.codeInit', $qb->expr()->literal($codeInit.'%')));
        }
        return $qb;
    }

    protected function critereNumeroAppel(QueryBuilder $qb, $numeroAppel)
    {
        if($numeroAppel != ''){
            $qb->andWhere($qb->expr()->like('n.numero', $qb->expr()->literal($numeroAppel.'%')));
        }
        return $qb;
    }

    protected function critereNom(QueryBuilder $qb, $nom)
    {
        if($nom != ''){
            $qb->andWhere($qb->expr()->like('a.nom', $qb->expr()->literal($nom.'%')));
        }
        return $qb;
    }

    protected function criterePrenoms(QueryBuilder $qb, $prenoms)
    {
        if($prenoms != ''){
            $qb->andWhere($qb->expr()->like('a.prenoms', $qb->expr()->literal($prenoms.'%')));
        }
        return $qb;
    }

    protected function critereInitStatus(QueryBuilder $qb, $initStatus = null)
    {
        if(!is_null($initStatus) && $initStatus != ''){
            if($initStatus==0){
                $qb->andWhere(
                    $qb->expr()->orX(
                        $qb->expr()->eq('a.initStatus', ':initStatus'),
                        $qb->expr()->isNull('a.initStatus')
                    )
                )
                    ->setParameter('initStatus', intval($initStatus))
                ;
            }else{
                $qb->andWhere($qb->expr()->eq('a.initStatus', ':initStatus'))->setParameter('initStatus', intval($initStatus));
            }

        }
        return $qb;
    }

    public function getAgentsBuilder(Region $region = null)
    {
        $qb = $this->createDefaultBuilder();
        $qb->where($qb->expr()->eq('q.id', ':profile'))
            ->setParameter('profile', Profile::PROFILE_AGENT_FORMEN)
        ;
        if(!is_null($region)){
            $qb->andWhere($qb->expr()->eq('r', ':region'))
                ->setParameter('region', $region)
            ;
        }
        return $this->myDefaultFilter($qb);
    }

    public function getSociologuesBuilder(Region $region = null)
    {
        $qb = $this->createDefaultBuilder();
        $qb->where($qb->expr()->eq('q.id', ':profile'))
            ->setParameter('profile', Profile::PROFILE_SOCIOLOGUE)
        ;
        if(!is_null($region)){
            $qb->andWhere($qb->expr()->eq('r', ':region'))
                ->setParameter('region', $region)
            ;
        }
        return $this->myDefaultFilter($qb);
    }

    public function getDirecteursBuilder(Region $region = null)
    {
        $qb = $this->createDefaultBuilder();
        $qb->where($qb->expr()->eq('q.id', ':profile'))
            ->setParameter('profile', Profile::PROFILE_DIRECTEUR)
        ;
        if(!is_null($region)){
            $qb->andWhere($qb->expr()->eq('r', ':region'))
                ->setParameter('region', $region)
            ;
        }
        return $this->myDefaultFilter($qb);
    }

    public function getAgents(Region $region = null)
    {
        return $this->getAgentsBuilder($region)->getQuery()->getResult();
    }

    public function getSociologues(Region $region = null)
    {
        return $this->getSociologuesBuilder($region)->getQuery()->getResult();
    }

    public function getDirecteurs(Region $region = null)
    {
        return $this->getDirecteursBuilder($region)->getQuery()->getResult();
    }

    public function getAgentsByRegionsIn(array $list)
    {
        $qb = $this->getAgentsBuilder()
            ->leftJoin('l.region', 're')
        ;
        $qb->andWhere($qb->expr()->orX($qb->expr()->in('r.id', ':list'), $qb->expr()->in('re.id', ':list')))
            ->setParameter('list', $list)
        ;
        return $qb->getQuery()->getResult();
    }

    public function getAgentsByLocalitesIn(array $list)
    {
        $qb = $this->getAgentsBuilder();
        $qb->andWhere($qb->expr()->in('l.id', ':list'))->setParameter('list', $list);
        return $qb->getQuery()->getResult();
    }

    public function getSociologuesByRegionsIn(array $list)
    {
        $qb = $this->getSociologuesBuilder();
        $qb->andWhere($qb->expr()->in('r.id', ':list'))->setParameter('list', $list);
        return $qb->getQuery()->getResult();
    }

    public function getSociologuesByLocalitesIn(array $list)
    {
        $qb = $this->getSociologuesBuilder();
        $qb->andWhere($qb->expr()->in('l.id', ':list'))->setParameter('list', $list);
        return $qb->getQuery()->getResult();
    }

    public function getDirecteursByRegionsIn(array $list)
    {
        $qb = $this->getDirecteursBuilder();
        $qb->andWhere($qb->expr()->in('r.id', ':list'))->setParameter('list', $list);
        return $qb->getQuery()->getResult();
    }

    public function getDirecteursByLocalitesIn(array $list)
    {
        $qb = $this->getDirecteursBuilder();
        $qb->andWhere($qb->expr()->in('l.id', ':list'))->setParameter('list', $list);
        return $qb->getQuery()->getResult();
    }

    public function getAgentsFormenByRegionBuilder(Region $region = null)
    {
        $qb = $this->getAgentsBuilder();
        $qb->andWhere($qb->expr()->eq('a.region', ':region'))
            ->setParameter('region', $region);
        return $qb;
    }

    public function getAgentsFormenByRegion(Region $region = null)
    {
        return $this->getAgentsFormenByRegionBuilder($region)->getQuery()->getResult();
    }

    public function getByRegionAndMustInitializedBuilder(Region $region)
    {
        $qb = $this->createQueryBuilder('a')
            ->leftJoin('a.qualification', 'q')
        ;
        $qb->where(
            $qb->expr()->andX(
                $qb->expr()->in('q.id', ':mustInitialized'),
                $qb->expr()->eq('a.region', ':region')
            )
        )
            ->setParameter('mustInitialized', Profile::getAgentsInitializedArray())
            ->setParameter('region', $region)
        ;
        return $qb;
    }

    public function getByRegionAndMustInitialized(Region $region){
        return $this->getByRegionAndMustInitializedBuilder($region)->getQuery()->getResult();
    }

    public function getByRegionNotUserBuilder(Region $region = null)
    {
        $qb = $this->createDefaultBuilder();
        if(!is_null($region)){
            $qb->andWhere($qb->expr()->eq('a.region', ':region'))
                ->setParameter('region', $region)
            ;
        }
//        $qb->andWhere($qb->expr()->isNull('u'));
        return $qb;
    }

    public function getByRegionNotUser(Region $region = null)
    {
        return $this->getByRegionNotUserBuilder()->getQuery()->getResult();
    }

    public function createDefaultBuilder()
    {
        $qb = $this->createQueryBuilder('a');
        $qb = $this->myDefaultSelectAll($qb);
        $qb = $this->myDefaultFilter($qb);
        return $qb;
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb->leftJoin('a.localites', 'l')
                ->addSelect('l')
            ->leftJoin('a.numeroAppel', 'n')
                ->addSelect('n')
            ->leftJoin('a.region', 'r')
                ->addSelect('r')
            ->leftJoin('a.user', 'u')
                ->addSelect('u')
            ->leftJoin('a.qualification', 'q')
                ->addSelect('q')
        ;

        return $qb;
    }

    protected function myDefaultOrder(QueryBuilder $qb)
    {
        $qb->orderBy('a.createdAt', 'DESC')
            ->addOrderBy('a.id', 'DESC')
        ;

        return $qb;
    }

    protected function defaultUserFilter(QueryBuilder $qb, User $user = null)
    {
        /*if($user && $user->isLoadRegional()){
            $qb->andWhere($qb->expr()->eq('a.region', ':region'))
                ->setParameter('region', $user->getRegion())
            ;
        }*/
        return $qb;
    }

    protected function myDefaultFilter(QueryBuilder $qb)
    {
        $site = ParameterFile::loadSite();
        if(!is_null($site)) {
            $qb->andWhere($qb->expr()->eq('r.id', ':region'))
                ->setParameter('region', $site);
        }
        return $qb;
    }
}
