<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Sofie\AdminBundle\Entity\Config;
use Sofie\AdminBundle\Model\ParameterFile;

/**
 * AppelTelephoniqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppelTelephoniqueRepository extends EntityRepository
{
    public function getByPanne(Panne $panne = null)
    {
        $qb = $this->createQueryBuilder('a');
        $qb = $this->myDefaultSelectAll($qb);
        $qb->where($qb->expr()->eq('p', ':panne'))
            ->setParameter('panne', $panne)
        ;
        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery()->getResult();
    }

    public function getAll($offset=Config::DEFAULT_OFFSET_PAGINATOR, $page = 1)
    {
        return Pagination::renderPagination($this->getAllQuery(), $offset, $page);
    }

    public  function getAllQuery()
    {
        $qb = $this->createQueryBuilder('a');
        $qb = $this->myDefaultSelectAll($qb);
        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    public function getTotalByCriteres(array $criteres=array())
    {
        return $this->getCritereQuery($criteres)->getResult();
    }

    public function getByCriteres(array $criteres=array(), $offset=Config::DEFAULT_OFFSET_PAGINATOR, $page=1)
    {
        return Pagination::renderPagination($this->getCritereQuery($criteres), $offset, $page);
    }

    public function getCritereQuery(array $criteres = array())
    {
        $qb = $this->createQueryBuilder('a');
        $qb = $this->myDefaultSelectAll($qb);

        // Critère date min
        if(array_key_exists('dmin', $criteres) && !empty($criteres['dmin'])){
            $qb = $this->critereDateMin($qb, $criteres['dmin']);
        }
        // Critère date max
        if(array_key_exists('dmax', $criteres) && !empty($criteres['dmax'])){
            $qb = $this->critereDateMax($qb, $criteres['dmax']);
        }
        // Critère panne
        if(array_key_exists('panne', $criteres) && $criteres['panne'] != ''){
            $qb = $this->criterePanne($qb, $criteres['panne']);
        }
        // Critère motif
        if(array_key_exists('motif', $criteres) && !empty($criteres['motif'])){
            $qb = $this->critereMotif($qb, $criteres['motif']);
        }
        // Critère numeroAppel
        if(array_key_exists('numeroAppel', $criteres) && $criteres['numeroAppel'] != ''){
            $qb = $this->critereNumeroAppel($qb, $criteres['numeroAppel']);
        }
        // Critère origine
        if(array_key_exists('origine', $criteres) && $criteres['origine'] instanceof Profile){
            $qb = $this->critereOrigine($qb, $criteres['origine']);
        }
        // Critère region
        if(array_key_exists('region', $criteres) && $criteres['region'] instanceof Region){
            $qb = $this->critereRegion($qb, $criteres['region']);
        }
        // Critère ouvrage
        if(array_key_exists('ouvrage', $criteres) && $criteres['ouvrage'] != ''){
            $qb = $this->critereOuvrage($qb, $criteres['ouvrage']);
        }

        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    protected function critereDateMin(QueryBuilder $qb, \DateTime $dmin = null)
    {

        if($dmin && $dmin instanceof \DateTime){
            $qb->andWhere($qb->expr()->gte('a.dateAppel', ':dmin'))->setParameter('dmin', $dmin->setTime(0,0,0));
        }
        return $qb;
    }

    protected function critereDateMax(QueryBuilder $qb, \DateTime $dmax = null)
    {
        if($dmax && $dmax instanceof \DateTime){
            $qb->andWhere($qb->expr()->lte('a.dateAppel', ':dmax'))->setParameter('dmax', $dmax->setTime(0,0,0));
        }
        return $qb;
    }

    protected function criterePanne(QueryBuilder $qb, $panne)
    {
        if($panne != ''){
            $qb->andWhere($qb->expr()->like('p.numero', $qb->expr()->literal($panne.'%')));
        }
        return $qb;
    }

    protected function critereMotif(QueryBuilder $qb, $motif)
    {
        if(array_key_exists($motif, AppelTelephonique::getMotifArrayAssoc())){
            $qb->andWhere($qb->expr()->eq('a.motif', ':motif'))
                ->setParameter('motif', $motif)
            ;
        }
        return $qb;
    }

    protected function critereNumeroAppel(QueryBuilder $qb, $numeroAppel)
    {
        if($numeroAppel != ''){
            $qb->andWhere($qb->expr()->like('n.numero', $qb->expr()->literal($numeroAppel.'%')));
        }
        return $qb;
    }

    protected function critereOrigine(QueryBuilder $qb, Profile $origine=null)
    {
        if(!is_null($origine)){
            $qb->andWhere($qb->expr()->eq('pro', ':origine'))
                ->setParameter('origine', $origine);
        }
        return $qb;
    }

    protected function critereRegion(QueryBuilder $qb, Region $region = null)
    {
        if(!is_null($region)){
            $qb->andWhere($qb->expr()->eq('r', ':region'))
                ->setParameter('region', $region);
        }
        return $qb;
    }

    protected function critereOuvrage(QueryBuilder $qb, $ouvrage)
    {
        if($ouvrage != ''){
            $qb->andWhere(
                $qb->expr()->orX(
                    $qb->expr()->like('o.code', $qb->expr()->literal($ouvrage.'%')),
                    $qb->expr()->like('o.codeOuvrageProgres', $qb->expr()->literal($ouvrage.'%'))
                )
            );
        }
        return $qb;
    }

    public function getByNumeroAppel(NumeroAppel $numeroAppel=null, $offset=Config::DEFAULT_OFFSET_PAGINATOR, $page=1)
    {
        return Pagination::renderPagination($this->getByNumeroAppelQuery($numeroAppel), $offset, $page);
    }

    public function getByNumeroAppelQuery(NumeroAppel $numeroAppel = null)
    {
        if($numeroAppel){
            $qb = $this->createDefaultBuilder();
            $qb->where($qb->expr()->eq('n', ':numeroAppel'))
                ->setParameter('numeroAppel', $numeroAppel);
            $qb = $this->myDefaultOrder($qb);
            return $qb->getQuery();
        }
        return null;
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb->leftJoin('a.numeroAppel', 'n')
                ->addSelect('n')
            ->leftJoin('a.panne', 'p')
                ->addSelect('p')
            ->leftJoin('p.ouvrage', 'o')
                ->addSelect('o')
            ->leftJoin('o.localite', 'l')
                ->addSelect('l')
            ->leftJoin('l.region', 'r')
                ->addSelect('r')
            ->leftJoin('n.agent', 'ag')
                ->addSelect('ag')
            ->leftJoin('n.comite', 'c')
                ->addSelect('c')
            ->leftJoin('n.reparateur', 're')
                ->addSelect('re')
            ->leftJoin('n.profile', 'pro')
                ->addSelect('pro')
        ;

        return $qb;
    }

    protected function createDefaultBuilder()
    {
        $qb = $this->createQueryBuilder('a');
        $qb = $this->myDefaultSelectAll($qb);
        $qb = $this->myDefaultFilter($qb);
        return $qb;
    }

    protected function myDefaultOrder(QueryBuilder $qb)
    {
        $qb->orderBy('a.id', 'DESC');

        return $qb;
    }

    protected function myDefaultFilter(QueryBuilder $qb)
    {
        $site = ParameterFile::loadSite();
        if(!is_null($site) && intval($site)>0){
            $qb->andWhere($qb->expr()->eq('r.id', ':region'))
                ->setParameter('region', $site)
            ;
        }
        return $qb;
    }
}
