<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Sofie\AdminBundle\Entity\Config;
use Sofie\AdminBundle\Model\ParameterFile;
use Sofie\UserBundle\Entity\User;

/**
 * CollecteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollecteRepository extends EntityRepository
{
    public function getNextId()
    {
        return intval($this->createQueryBuilder('c')->select('MAX(c.id)')->getQuery()->getSingleScalarResult())+1;
    }

    public function get($id)
    {
        $qb = $this->createDefaultBuilder();
        $qb->andWhere($qb->expr()->eq('c.id', ':id'))
            ->setParameter('id', intval($id))
        ;
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getFullByOuvrage(Ouvrage $ouvrage=null)
    {
        return $this->getByOuvrageBuilder($ouvrage)->getQuery()->getResult();
    }

    public function getByOuvrage(Ouvrage $ouvrage = null, $offset=Config::DEFAULT_OFFSET_PAGINATOR, $page=1)
    {
        return Pagination::renderPagination($this->getByOuvrageBuilder($ouvrage)->getQuery(), $offset, $page);
    }

    public function getByOuvrageBuilder(Ouvrage $ouvrage = null)
    {
        $qb = $this->createDefaultBuilder();
        $qb->where($qb->expr()->eq('o', ':ouvrage'))
            ->setParameter('ouvrage', $ouvrage)
        ;
        $qb = $this->myDefaultOrder($qb);
        return $qb;
    }

    public function getAll($offset=Config::DEFAULT_OFFSET_PAGINATOR, $page = 1)
    {
        return Pagination::renderPagination($this->getAllQuery(), $offset, $page);
    }

    public  function getAllQuery()
    {
        $qb = $this->createDefaultBuilder();
        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    public function getTotalByCriteres(array $criteres=array())
    {
        return $this->getCritereQuery($criteres)->getResult();
    }

    public function getByCriteres(array $criteres=array(), $offset=Config::DEFAULT_OFFSET_PAGINATOR, $page=1)
    {
        return Pagination::renderPagination($this->getCritereQuery($criteres), $offset, $page);
    }

    public function getCritereQuery(array $criteres = array())
    {
        $qb = $this->createQueryBuilder('c');
        $qb = $this->myDefaultSelectAll($qb);

        // Critère ouvrage
        if(array_key_exists('ouvrage', $criteres) && $criteres['ouvrage'] instanceof Ouvrage){
            $qb = $this->critereOuvrage($qb, $criteres['ouvrage']);
        }
        // Critère validated
        if(array_key_exists('validated', $criteres) && $criteres['validated'] != ''){
            $qb = $this->critereValidated($qb, $criteres['validated']);
        }
        // Critère operateur
        if(array_key_exists('operateur', $criteres) && $criteres['operateur'] != ''){
            $qb = $this->critereOperateur($qb, $criteres['operateur']);
        }
        // Critère agentSaisie
        if(array_key_exists('agentSaisie', $criteres) && $criteres['agentSaisie'] != ''){
            $qb = $this->critereAgentSaisie($qb, $criteres['agentSaisie']);
        }

        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    protected function critereOuvrage(QueryBuilder $qb, Ouvrage $ouvrage=null)
    {
        if(!is_null($ouvrage)){
            $qb->andWhere($qb->expr()->eq('o', ':ouvrage'))
                ->setParameter('ouvrage', $ouvrage);
        }
        return $qb;
    }

    protected function critereValidated(QueryBuilder $qb, $validated = null)
    {
        if(!is_null($validated) && $validated != ''){
            if($validated==0){
                $qb->andWhere(
                    $qb->expr()->orX(
                        $qb->expr()->eq('c.validated', ':validated'),
                        $qb->expr()->isNull('c.validated')
                    )
                )
                    ->setParameter('validated', $validated)
                ;
            }else{
                $qb->andWhere($qb->expr()->eq('c.validated', ':validated'))->setParameter('validated', $validated);
            }

        }
        return $qb;
    }

    protected function critereOperateur(QueryBuilder $qb, $operateur = null)
    {
        if(!is_null($operateur) && $operateur != ''){
            $qb->andWhere($qb->expr()->like('c.nomOperateur', $qb->expr()->literal($operateur.'%')));
        }
        return $qb;
    }

    protected function critereAgentSaisie(QueryBuilder $qb, $agentSaisie = null)
    {
        if(!is_null($agentSaisie) && $agentSaisie != ''){
            $qb->andWhere($qb->expr()->like('c.nomAgentSaisie', $qb->expr()->literal($agentSaisie.'%')));
        }
        return $qb;
    }

    protected function createDefaultBuilder()
    {
        $qb = $this->createQueryBuilder('c');
        $qb = $this->myDefaultSelectAll($qb);
        return $qb;
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb->leftJoin('c.ouvrage', 'o')
                ->addSelect('o')
        ;

        return $qb;
    }

    protected function myDefaultOrder(QueryBuilder $qb)
    {
        $qb->orderBy('c.id', 'DESC');

        return $qb;
    }

    protected function defaultUserFilter(QueryBuilder $qb, User $user = null)
    {
        /*if($user && $user->isLoadRegional()){
            $qb->leftJoin('o.localite', 'l')
                ->andWhere($qb->expr()->eq('l.region', ':region'))
                ->setParameter('region', $user->getRegion())
            ;
        }*/
        return $qb;
    }

    protected function myDefaultFilter(QueryBuilder $qb)
    {
        $site = ParameterFile::loadSite();
        if(!is_null($site)) {
            $qb->leftJoin('o.localite', 'l')
                ->leftJoin('l.region', 'r')
                ->andWhere($qb->expr()->eq('r.id', ':region'))
                ->setParameter('region', $site);
        }
        return $qb;
    }
}
