<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Sofie\AdminBundle\Entity\Config;
use Sofie\AdminBundle\Model\ParameterFile;
use Sofie\UserBundle\Entity\User;

/**
 * ComiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComiteRepository extends EntityRepository
{
    public function get($id)
    {
        $qb = $this->createDefaultBuilder();
        $qb->andWhere($qb->expr()->eq('c.id', ':id'))->setParameter('id', intval($id));
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getAll($offset=Config::DEFAULT_OFFSET_PAGINATOR, $page = 1)
    {
        return Pagination::renderPagination($this->getAllQuery(), $offset, $page);
    }

    public function getFullAll()
    {
        return $this->getAllQuery()->getResult();
    }

    public function getNextId()
    {
        return intval($this->createQueryBuilder('c')->select('MAX(c.id)')->getQuery()->getSingleScalarResult())+1;
    }

    public  function getAllQuery()
    {
        $qb = $this->createDefaultBuilder();
        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    public function getTotalByCriteres(array $criteres=array())
    {
        return $this->getCritereQuery($criteres)->getResult();
    }

    public function getByCriteres(array $criteres, $offset=Config::DEFAULT_OFFSET_PAGINATOR, $page=1)
    {
        return Pagination::renderPagination($this->getCritereQuery($criteres), $offset, $page);
    }
    public function getCritereQuery(array $criteres = array())
    {
        $qb = $this->createDefaultBuilder();

        // Critère région
        if(array_key_exists('region', $criteres)){
            $qb = $this->critereRegion($qb, $criteres['region']);
        }
        // Critère localité
        if(array_key_exists('localite', $criteres)){
            $qb = $this->critereLocalite($qb, $criteres['localite']);
        }
        // Critère codeInit
        if(array_key_exists('codeInit', $criteres) && $criteres['codeInit'] != ''){
            $qb = $this->critereCodeInit($qb, $criteres['codeInit']);
        }
        // Critère numeroAppel
        if(array_key_exists('numeroAppel', $criteres) && $criteres['numeroAppel'] != ''){
            $qb = $this->critereNumeroAppel($qb, $criteres['numeroAppel']);
        }
        // Critère nom
        if(array_key_exists('nom', $criteres) && $criteres['nom'] != ''){
            $qb = $this->critereNom($qb, $criteres['nom']);
        }
        // Critère initStatus
        if(array_key_exists('initStatus', $criteres) && $criteres['initStatus'] != ''){
            $qb = $this->critereInitStatus($qb, $criteres['initStatus']);
        }

        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    protected function critereRegion(QueryBuilder $qb, Region $region = null)
    {
        if($region){
            $qb->andWhere($qb->expr()->eq('l.region', ':region'))->setParameter('region', $region);
        }
        return $qb;
    }

    protected function critereLocalite(QueryBuilder $qb, Localite $localite = null)
    {
        if($localite){
            $qb->andWhere($qb->expr()->eq('l', ':localite'))->setParameter('localite', $localite);
        }
        return $qb;
    }

    protected function critereCodeInit(QueryBuilder $qb, $codeInit)
    {
        if($codeInit != ''){
            $qb->andWhere($qb->expr()->like('c.codeInit', $qb->expr()->literal($codeInit.'%')));
        }
        return $qb;
    }

    protected function critereNumeroAppel(QueryBuilder $qb, $numeroAppel)
    {
        if($numeroAppel != ''){
            $qb->andWhere($qb->expr()->like('n.numero', $qb->expr()->literal($numeroAppel.'%')));
        }
        return $qb;
    }

    protected function critereNom(QueryBuilder $qb, $nom)
    {
        if($nom != ''){
            $qb->andWhere($qb->expr()->like('c.nom', $qb->expr()->literal($nom.'%')));
        }
        return $qb;
    }

    protected function critereInitStatus(QueryBuilder $qb, $initStatus = null)
    {
        if(!is_null($initStatus) && $initStatus != ''){
            if($initStatus==0){
                $qb->andWhere(
                    $qb->expr()->orX(
                        $qb->expr()->eq('c.initStatus', ':initStatus'),
                        $qb->expr()->isNull('c.initStatus')
                    )
                )
                    ->setParameter('initStatus', intval($initStatus))
                ;
            }else{
                $qb->andWhere($qb->expr()->eq('c.initStatus', ':initStatus'))->setParameter('initStatus', intval($initStatus));
            }

        }
        return $qb;
    }

    public function getByRegionsIn(array $list)
    {
        $qb = $this->createQueryBuilder('c')
            ->innerJoin('c.localite', 'l')
            ->innerJoin('l.region', 'r')
        ;
        $qb->where($qb->expr()->in('r.id', ':list'))->setParameter('list', $list);

        return $qb->getQuery()->getResult();
    }

    public function getByLocalitesIn(array $list)
    {
        $qb = $this->createQueryBuilder('c')
            ->leftJoin('c.localite', 'l')
        ;
        $qb->where($qb->expr()->in('l.id', ':list'))->setParameter('list', $list);

        return $qb->getQuery()->getResult();
    }

    public  function getByLoclaiteAndNotOuvrage(Localite $localite = null)
    {
        $qb = $this->createQueryBuilder('c')
            ->leftJoin('c.localite', 'l')
            ->leftJoin('c.ouvrage', 'o')
        ;
        $qb->where($qb->expr()->andX(
            $qb->expr()->eq('l', ':localite'),
            $qb->expr()->isNull('o')
        ))
            ->setParameter('localite', $localite)
        ;

        return $qb->getQuery()->getResult();
    }

    public function getByUserRegionBuilder()
    {
        $qb = $this->createQueryBuilder('c')
            ->leftJoin('c.localite', 'l')
                ->addSelect('l')
            ->leftJoin('l.region', 'r')
        ;
        return $this->myDefaultFilter($qb);
    }

    public function getByUserRegion()
    {
        return $this->getByUserRegionBuilder()->getQuery()->getResult();
    }

    public function getByLocaliteBuilder(Localite $localite = null)
    {
        if(!is_null($localite)){
            $qb = $this->createQueryBuilder('c');
            $qb->where($qb->expr()->eq('c.localite', ':localite'))
                ->setParameter('localite', $localite)
                ->orderBy('c.nom', 'ASC')
            ;
            return $qb;
        }
        return null;
    }

    public function getByLocalite(Localite $localite = null)
    {
        $qb = $this->getByLocaliteBuilder($localite);
        if(!is_null($qb)){
            return $qb->getQuery()->getResult();
        }
        return array();
    }

    public function getByLocaliteIdAndFreeBuilder($localiteId, $currentId)
    {
        $qb = $this->createQueryBuilder('c')
            ->leftJoin('c.localite', 'l')
            ->leftJoin('c.ouvrage', 'o')
        ;
        $qb->where(
            $qb->expr()->andX(
                $qb->expr()->eq('l.id', ':localite'),
                $qb->expr()->orX(
                    $qb->expr()->eq('c.id', ':current'),
                    $qb->expr()->isNull('o')
                )
            )
        )
            ->setParameter('current', $currentId)
            ->setParameter('localite', $localiteId)
            ->orderBy('c.nom', 'ASC')
        ;
        return $qb;
    }

    public function getByLocaliteIdAndFree($localiteId, $currentId)
    {
        return $this->getByLocaliteIdAndFreeBuilder($localiteId, $currentId)->getQuery()->getResult();
    }

    public function createDefaultBuilder()
    {
        $qb = $this->createQueryBuilder('c');
        $qb = $this->myDefaultSelectAll($qb);
        $qb = $this->myDefaultFilter($qb);
        return $qb;
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb->leftJoin('c.localite', 'l')
            ->addSelect('l')
            ->leftJoin('l.region', 'r')
            ->addSelect('r')
            ->leftJoin('c.numeroAppel', 'n')
            ->addSelect('n')
            ->leftJoin('c.ouvrage', 'o')
                ->addSelect('o')
        ;

        return $qb;
    }

    protected function myDefaultOrder(QueryBuilder $qb)
    {
        $qb->orderBy('c.updatedAt', 'DESC')
            ->addOrderBy('c.createdAt', 'DESC')
            ->addOrderBy('c.id', 'DESC')
            ->addOrderBy('c.nom', 'ASC')
        ;

        return $qb;
    }

    protected function myDefaultFilter(QueryBuilder $qb)
    {
        $site = ParameterFile::loadSite();
        if(!is_null($site) && intval($site)>0){
            $qb->andWhere($qb->expr()->eq('r.id', ':region'))
                ->setParameter('region', $site)
            ;
        }
        return $qb;
    }

    protected function defaultUserFilter(QueryBuilder $qb, User $user = null)
    {
        /*if($user && $user->isLoadRegional()){
            $qb->andWhere($qb->expr()->eq('l.region', ':region'))
                ->setParameter('region', $user->getRegion())
            ;
        }*/
        return $qb;
    }
}
