<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoupeGeologiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoupeGeologiqueRepository extends EntityRepository
{
    public function insert(CoupeGeologique $coupeGeologique, $data)
    {
        $con = $this->getEntityManager()->getConnection();

        if($coupeGeologique->getId() != null){
            $data['IDCoupegeologique'] = $coupeGeologique->getId();
        }
        if(isset($data['position'])){
            unset($data['position']);
        }
        if($coupeGeologique->getOuvrage()){
            $data['IDOuvrage'] = $coupeGeologique->getOuvrage()->getId();
        }
        $con->insert('t_coupegeologique', $data);
    }

    public function getNextId()
    {
        return intval($this->createQueryBuilder('c')->select('MAX(c.id)')->getQuery()->getSingleScalarResult())+1;
    }
}
