<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipementForageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipementForageRepository extends EntityRepository
{
    public function insert(EquipementForage $equipementForage, array $data)
    {
        $con = $this->getEntityManager()->getConnection();

        if($equipementForage->getId() != null){
            $data['IDEquipementforage'] = $equipementForage->getId();
        }
        if(isset($data['position'])){
            unset($data['position']);
        }
        if($equipementForage->getOuvrage()){
            $data['IDOuvrage'] = $equipementForage->getOuvrage()->getId();
        }
        $con->insert('t_equipementforage', $data);
    }

    public function getNextId()
    {
        return intval($this->createQueryBuilder('e')->select('MAX(e.id)')->getQuery()->getSingleScalarResult())+1;
    }
}
