<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EssaisPompageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EssaisPompageRepository extends EntityRepository
{
    public function insert(EssaisPompage $essaisPompage, array $data)
    {
        $con = $this->getEntityManager()->getConnection();

        if($essaisPompage->getId() != null){
            $data['IDEssaispompage'] = $essaisPompage->getId();
        }
        if(isset($data['Date'])){
            unset($data['Date']);
            $data['`Date`'] = $essaisPompage->getDate()->format('Y-m-d');
        }
        if(isset($data['position'])){
            unset($data['position']);
        }
        if($essaisPompage->getOuvrage()){
            $data['IDOuvrage'] = $essaisPompage->getOuvrage()->getId();
        }
        $con->insert('t_essaispompage', $data);
    }

    public function getNextId()
    {
        return intval($this->createQueryBuilder('e')->select('MAX(e.id)')->getQuery()->getSingleScalarResult())+1;
    }
}
