<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\QueryBuilder;
use Sofie\AdminBundle\Entity\Config;
use Sofie\AdminBundle\Model\ParameterFile;
use Sofie\UserBundle\Entity\User;

/**
 * LocaliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocaliteRepository extends EntityRepository
{
    public function getNextId()
    {
        return intval($this->createQueryBuilder('l')->select('MAX(l.id)')->getQuery()->getSingleScalarResult())+1;
    }

    public function get($id){
        $qb = $this->createQueryBuilder('l');
        $qb = $this->myDefaultSelectAll($qb);
        $qb = $this->myDefaultFilter($qb);
        $qb->andWhere($qb->expr()->eq('l.id', ':id'))->setParameter('id', intval($id));
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getFullAll()
    {
        return $this->getAllQuery()->getResult();
    }

    public function getAll($offset=Config::DEFAULT_OFFSET_PAGINATOR, $page = 1)
    {
        return Pagination::renderPagination($this->getAllQuery(), $offset, $page);
    }

    public  function getAllQuery()
    {
        $qb = $this->createQueryBuilder('l');
        $qb = $this->myDefaultSelectAll($qb);
        $qb = $this->myDefaultFilter($qb);
        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    public function getByRegionBuilder(Region $region = null){
        $qb = $this->createQueryBuilder('l')
            ->leftJoin('l.region', 'r')
            ->leftJoin('l.reparateur', 're')
                ->addSelect('re')
            ->leftJoin('l.agentForma', 'a')
                ->addSelect('a')
        ;
        $qb->andWhere($qb->expr()->eq('r', ':region'))
            ->setParameter('region', $region)
        ;
        return $qb;
    }

    public function getByRegion(Region $region){
        return $this->getByRegionBuilder($region)->getQuery()->getResult();
    }

    public function getByUserRegionBuilder(){
        $qb = $this->createQueryBuilder('l');
        $qb = $this->myDefaultFilter($qb);
        return $qb;
    }

    public function getByUserRegion()
    {
        return $this->getByUserRegionBuilder()->getQuery()->getResult();
    }

    public function getTotalByCriteres(array $criteres = array())
    {
        return $this->getCritereQuery($criteres)->getResult();
    }

    public function getByCriteres(array $criteres=array(), $offet=Config::DEFAULT_OFFSET_PAGINATOR, $page=1)
    {
        return Pagination::renderPagination($this->getCritereQuery($criteres), $offet, $page);
    }

    public function getCritereQuery(array $criteres = array())
    {
        $qb = $this->createQueryBuilder('l');
        $qb = $this->myDefaultSelectAll($qb);
        $qb = $this->myDefaultFilter($qb);

        // Critère région
        if(array_key_exists('region', $criteres)){
            $qb = $this->critereRegion($qb, $criteres['region']);
        }
        // Critère nom
        if(array_key_exists('nom', $criteres) && $criteres['nom'] != ''){
            $qb = $this->critereNom($qb, $criteres['nom']);
        }

        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    /**
     * @param QueryBuilder $qb
     * @param Region $region
     * @return QueryBuilder
     */
    protected function critereRegion(QueryBuilder $qb, Region $region = null)
    {
        if($region){
            $qb->andWhere($qb->expr()->eq('r', ':region'))->setParameter('region', $region);
        }
        return $qb;
    }

    protected function critereNom(QueryBuilder $qb, $nom = null)
    {
        if($nom != ''){
            $qb->andWhere($qb->expr()->like('l.nom', $qb->expr()->literal($nom.'%')));
        }
        return $qb;
    }

    /**
     * @param array $list
     * @return array
     */
    public function getByRegionsIn(array $list)
    {
        $qb = $this->createQueryBuilder('l')
            ->innerJoin('l.region', 'r')
        ;
        $qb->where($qb->expr()->in('r.id', ':list'))->setParameter('list', $list);

        return $qb->getQuery()->getResult();
    }

    /**
     * @param QueryBuilder $qb
     * @return QueryBuilder
     */
    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb->leftJoin('l.region', 'r')
//                ->addSelect('r')
//            ->leftJoin('r.config', 'conf')
//                ->addSelect('conf')
            ->leftJoin('l.agentForma', 'a')
                ->addSelect('a')
            ->leftJoin('l.reparateur', 'rep')
                ->addSelect('rep')
            ->leftJoin('l.comites', 'c')
                ->addSelect('c')
            ->leftJoin('l.ouvrages', 'o')
                ->addSelect('o')
        ;

        return $qb;
    }

    /**
     * Filter les locailité selon les profils utilisateur
     *
     * @param QueryBuilder $qb
     * @param User|null $user
     * @return QueryBuilder
     */
    protected function defaultUserFilter(QueryBuilder $qb, User $user = null)
    {
        /*if($user && $user->isLoadRegional()){
            $qb->andWhere($qb->expr()->eq('l.region', ':region'))
                ->setParameter('region', $user->getRegion())
            ;
        }*/
        return $qb;
    }

    /**
     * @param QueryBuilder $qb
     * @return QueryBuilder
     */
    protected function myDefaultOrder(QueryBuilder $qb)
    {
        $qb->orderBy('l.createdAt', 'DESC')
            ->addOrderBy('l.id', 'DESC')
        ;

        return $qb;
    }

    protected function myDefaultFilter(QueryBuilder $qb)
    {
        $site = ParameterFile::loadSite();
        if(!is_null($site) && intval($site)>0){
            $qb->andWhere($qb->expr()->eq('r.id', ':region'))
                ->setParameter('region', $site)
            ;
        }
        return $qb;
    }

}
