<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Sofie\AdminBundle\Entity\Config;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function getByPanne(Panne $panne = null)
    {
        $qb = $this->createQueryBuilder('n');
        $qb = $this->myDefaultSelectAll($qb);
        $qb->where($qb->expr()->eq('p', ':panne'))
            ->setParameter('panne', $panne)
        ;
        $qb = $this->myDefaultOrder($qb);

        return $qb->getQuery()->getResult();
    }

    public function getByNumeroAppel(NumeroAppel $numeroAppel, $offset=Config::DEFAULT_OFFSET_PAGINATOR, $page=1)
    {
        return Pagination::renderPagination($this->getByNumeroAppelQuery($numeroAppel), $offset, $page);
    }

    public function getByNumeroAppelQuery(NumeroAppel $numeroAppel = null)
    {
        if($numeroAppel){
            $qb = $this->createDefaultBuilder();
            $qb->where($qb->expr()->eq('num', ':numeroAppel'))
                ->setParameter('numeroAppel', $numeroAppel);
            $qb = $this->myDefaultOrder($qb);
            return $qb->getQuery();
        }
        return null;
    }

    public function getFullByCriteres(array $criteres=array())
    {
        return $this->getByCritersQuery($criteres)->getResult();
    }

    public function getByCritersQuery(array $criteres=array())
    {
        $qb = $this->createQueryBuilder('n');
        $qb = $this->myDefaultSelectAll($qb);

//        Critère panne
        if(array_key_exists('panne', $criteres) && $criteres['panne'] instanceof Panne){
            $qb = $this->criterePanne($qb, $criteres['panne']);
        }

        // Critère numeroAppel
        if(array_key_exists('numeroAppel', $criteres) && $criteres['numeroAppel'] instanceof NumeroAppel){
            $qb = $this->critereNumeroAppel($qb, $criteres['numeroAppel']);
        }

        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    protected function criterePanne(QueryBuilder $qb, Panne $panne)
    {
        $qb->where($qb->expr()->eq('p', ':panne'))
            ->setParameter('panne', $panne)
        ;
        return $qb;
    }

    protected function critereNumeroAppel(QueryBuilder $qb, NumeroAppel $numeroAppel)
    {
        $qb->where($qb->expr()->eq('num', ':numeroAppel'))
            ->setParameter('numeroAppel', $numeroAppel);
        return $qb;
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb->leftJoin('n.numeroAppel', 'num')
            ->addSelect('num')
            ->leftJoin('n.panne', 'p')
            ->addSelect('p')
        ;

        return $qb;
    }

    protected function createDefaultBuilder()
    {
        $qb = $this->createQueryBuilder('n');
        $qb = $this->myDefaultSelectAll($qb);
        return $qb;
    }

    protected function myDefaultOrder(QueryBuilder $qb)
    {
        $qb->orderBy('n.id', 'DESC');

        return $qb;
    }
}
