<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Sofie\AdminBundle\Entity\Config;

/**
 * NumeroAppelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumeroAppelRepository extends EntityRepository
{
    public function get($id)
    {
        $qb = $this->createDefaultBuilder();
        $qb->andWhere($qb->expr()->eq('n.id', ':id'))
            ->setParameter('id', intval($id))
        ;
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getAll($offset=Config::DEFAULT_OFFSET_PAGINATOR, $page = 1)
    {
        return Pagination::renderPagination($this->getAllQuery(), $offset, $page);
    }

    public  function getAllQuery()
    {
        $qb = $this->createQueryBuilder('n');
        $qb = $this->myDefaultSelectAll($qb);
        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    public function getFullByCriteres(array $criteres=array())
    {
        return $this->getCritereQuery($criteres)->getResult();
    }

    public function getByCriteres(array $criteres=array(), $offset=Config::DEFAULT_OFFSET_PAGINATOR, $page=1)
    {
        return Pagination::renderPagination($this->getCritereQuery($criteres), $offset, $page);
    }

    public function getCritereQuery(array $criteres = array())
    {
        $qb = $this->createQueryBuilder('n');
        $qb = $this->myDefaultSelectAll($qb);

        // Critère numéro
        if(array_key_exists('numero', $criteres)){
            $qb = $this->critereNumero($qb, $criteres['numero']);
        }
        // Critère agent
        if(array_key_exists('profile', $criteres)){
            $qb = $this->critereProfile($qb, $criteres['profile']);
        }
        // Critère acteur
        if(array_key_exists('acteur', $criteres)){
            $qb = $this->critereActeur($qb, $criteres['acteur']);
        }

        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    protected function critereNumero(QueryBuilder $qb, $numero = null)
    {
        if($numero){
            $qb->andWhere($qb->expr()->like('n.numero', $qb->expr()->literal($numero.'%')));
//            $qb->andWhere($qb->expr()->eq('n.numero', ':numero'))->setParameter('numero', $numero);
        }
        return $qb;
    }

    protected function critereProfile(QueryBuilder $qb, $profile = null)
    {
        if(boolval($profile)){
            $qb->andWhere($qb->expr()->eq('p', ':profile'))->setParameter('profile', $profile);
        }
        return $qb;
    }

    protected function critereActeur(QueryBuilder $qb, $acteur = null)
    {
        if($acteur){
            switch($acteur){
                case '1':
                    $numeros = $this->getEntityManager()
                        ->createQuery('SELECT n.id FROM SofieExpBundle:Agent a JOIN a.numeroAppel n')->getArrayResult();
                    $acteurs = $this->getArrayActeurNumeroId($numeros);
                    break;
                case '2':
                    $numeros = $this->getEntityManager()
                        ->createQuery('SELECT n.id FROM SofieExpBundle:Comite c JOIN c.numeroAppel n')->getArrayResult();
                    $acteurs = $this->getArrayActeurNumeroId($numeros);
                    break;
                case '3':
                    $numeros = $this->getEntityManager()
                        ->createQuery('SELECT n.id FROM SofieExpBundle:Reparateur r JOIN r.numeroAppel n')->getArrayResult();
                    $acteurs = $this->getArrayActeurNumeroId($numeros);
                    break;
                default:
                    $acteurs = array();
            }
            $qb->andWhere($qb->expr()->in('n', $acteurs));
        }
        return $qb;
    }

    protected function getArrayActeurNumeroId($numeros)
    {
        $acteurs = array();
        if(is_array($numeros)){
            for($i = 0; $i < count($numeros); $i++){
                foreach($numeros[$i] as $numId){
                    $acteurs[] = $numId;
                }
            }
        }
        return $acteurs;
    }

    public function getOne($id){
        $qb = $this->createDefaultBuilder();
        $qb->where($qb->expr()->eq('n.id', ':id'))
            ->setParameter('id', $id);
        return $qb->getQuery()->getOneOrNullResult();
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb->leftJoin('n.appels', 'a')
                ->addSelect('a')
            ->leftJoin('n.notifications', 'no')
                ->addSelect('no')
            ->leftJoin('n.profile', 'p')
                ->addSelect('p')
        ;

        return $qb;
    }

    protected function createDefaultBuilder()
    {
        $qb = $this->createQueryBuilder('n');
        $qb = $this->myDefaultSelectAll($qb);
        return $qb;
    }

    protected function myDefaultOrder(QueryBuilder $qb)
    {
        $qb->orderBy('n.id', 'DESC');

        return $qb;
    }
}
