<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\QueryBuilder;
use Sofie\AdminBundle\Entity\Config;
use Sofie\AdminBundle\Model\ParameterFile;
use Sofie\UserBundle\Entity\User;

/**
 * OuvrageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OuvrageRepository extends EntityRepository
{
    public function insert(Ouvrage $ouvrage, array $data)
    {
        $con = $this->getEntityManager()->getConnection();

        if($ouvrage->getId() != null){
            $data['IDOuvrage'] = $ouvrage->getId();
        }
        $data['CodeOuvrage'] = $ouvrage->getCode();
        if(isset($data['Usage'])){
            unset($data['Usage']);
            $data['`Usage`'] = $ouvrage->getUsage();
        }
        $con->insert('t_ouvrage', $data);
    }

    public function get($id)
    {
        $qb = $this->createQueryBuilder('o');
        $qb = $this->myDefaultSelectAll($qb);
        $qb->where($qb->expr()->eq('o.id', ':id'))
            ->setParameter('id', $id);
        ;
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getAll($offset=Config::DEFAULT_OFFSET_PAGINATOR, $page = 1)
    {
        return Pagination::renderPagination($this->getAllQuery(), $offset, $page);
    }

    public function getNextId()
    {
        return intval($this->createQueryBuilder('o')->select('MAX(o.id)')->getQuery()->getSingleScalarResult())+1;
    }

    public  function getAllQuery()
    {
        $qb = $this->createQueryBuilder('o');
        $qb = $this->myDefaultSelectAll($qb);
        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    public function getByCriteres(array $criteres=array(), $offset=Config::DEFAULT_OFFSET_PAGINATOR, $page=1)
    {
        return Pagination::renderPagination($this->getCritereQuery($criteres), $offset, $page);
    }

    public function getTotalByCriteres(array $criteres=array())
    {
        return $this->getCritereQuery($criteres)->getResult();
    }

    public function getCritereQuery(array $criteres = array())
    {
        $qb = $this->createQueryBuilder('o');
        $qb = $this->myDefaultSelectAll($qb);

        // Critère région
        if(array_key_exists('region', $criteres)){
            $qb = $this->critereRegion($qb, $criteres['region']);
        }
        // Critère localité
        if(array_key_exists('localite', $criteres)){
            $qb = $this->critereLocalite($qb, $criteres['localite']);
        }
        // Critère statut
        if(array_key_exists('statut', $criteres) && $criteres['statut'] != ''){
            $qb = $this->critereStatut($qb, $criteres['statut']);
        }
        // Critère code
        if(array_key_exists('code', $criteres) && $criteres['code'] != ''){
            $qb = $this->critereCode($qb, $criteres['code']);
        }
        // Critère numIRH
        if(array_key_exists('numIRH', $criteres) && $criteres['numIRH'] != ''){
            $qb = $this->critereNumIRH($qb, $criteres['numIRH']);
        }
        // Critère validated
        if(array_key_exists('validated', $criteres) && $criteres['validated'] != ''){
            $qb = $this->critereValidated($qb, $criteres['validated']);
        }

        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    protected function critereRegion(QueryBuilder $qb, Region $region = null)
    {
        if(!is_null($region)){
            $qb->andWhere($qb->expr()->eq('l.region', ':region'))->setParameter('region', $region);
        }
        return $qb;
    }

    protected function critereLocalite(QueryBuilder $qb, Localite $localite = null)
    {
        if(!is_null($localite)){
            $qb->andWhere($qb->expr()->eq('l', ':localite'))->setParameter('localite', $localite);
        }
        return $qb;
    }

    protected function critereStatut(QueryBuilder $qb, $statut = null)
    {
        if(!is_null($statut) && $statut != ''){
            $qb->andWhere($qb->expr()->eq('o.statutOuvrage', ':statut'))->setParameter('statut', $statut);
        }
        return $qb;
    }

    protected function critereCode(QueryBuilder $qb, $code = null)
    {
        if(!is_null($code) && $code != ''){
            $qb->andWhere(
                $qb->expr()->orX(
                    $qb->expr()->like('o.code', $qb->expr()->literal($code.'%')),
                    $qb->expr()->like('o.codeOuvrageProgres', $qb->expr()->literal($code.'%'))
                )
            );
        }
        return $qb;
    }

    protected function critereNumIRH(QueryBuilder $qb, $numIRH = null)
    {
        if(!is_null($numIRH) && $numIRH != ''){
            $qb->andWhere($qb->expr()->like('o.numIRH', $qb->expr()->literal($numIRH.'%')));
        }
        return $qb;
    }

    protected function critereValidated(QueryBuilder $qb, $validated = null)
    {
        if(!is_null($validated) && $validated != ''){
            if($validated==0){
                $qb->andWhere(
                    $qb->expr()->orX(
                        $qb->expr()->eq('o.validated', ':validated'),
                        $qb->expr()->isNull('o.validated')
                    )
                )
                    ->setParameter('validated', $validated)
                ;
            }else{
                $qb->andWhere($qb->expr()->eq('o.validated', ':validated'))->setParameter('validated', $validated);
            }

        }
        return $qb;
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb->leftJoin('o.comite', 'c')
                ->addSelect('c')
            ->leftJoin('o.localite', 'l')
                ->addSelect('l')
            ->leftJoin('o.coupeGeologiques', 'cg')
                ->addSelect('cg')
            ->leftJoin('o.equipementForages', 'ef')
                ->addSelect('ef')
            ->leftJoin('o.essaisPompages', 'ep')
                ->addSelect('ep')
            ->leftJoin('o.suiviPhysicoChimiques', 'spc')
                ->addSelect('spc')
            ->leftJoin('o.venuEauPrincipales', 'vep')
                ->addSelect('vep')
            ->leftJoin('o.pannes', 'p')
                ->addSelect('p')
            ->leftJoin('o.collectes', 'co')
                ->addSelect('co')
            ->leftJoin('l.region', 'r')
                ->addSelect('r')
        ;

        return $qb;
    }

    protected function defaultUserFilter(QueryBuilder $qb, User $user = null)
    {
        /*if($user && $user->isLoadRegional()){
            $qb->andWhere($qb->expr()->eq('l.region', ':region'))
                ->setParameter('region', $user->getRegion())
            ;
        }*/
        return $qb;
    }

    protected function myDefaultOrder(QueryBuilder $qb)
    {
        $qb->orderBy('o.id', 'DESC');

        return $qb;
    }

    protected function myDefaultFilter(QueryBuilder $qb)
    {
        $site = ParameterFile::loadSite();
        if(!is_null($site)) {
            $qb->andWhere($qb->expr()->eq('r.id', ':region'))
                ->setParameter('region', $site);
        }
        return $qb;
    }
}
