<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Sofie\AdminBundle\Entity\Config;
use Sofie\AdminBundle\Model\ParameterFile;
use Sofie\UserBundle\Entity\User;

/**
 * PanneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanneRepository extends EntityRepository
{
    public function get($id)
    {
        $qb = $this->createDefaultBuilder();
        $qb->andWhere($qb->expr()->eq('p.id', ':id'))
            ->setParameter('id', intval($id))
        ;
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getFullByOuvrage(Ouvrage $ouvrage = null)
    {
        return $this->getByOuvrageBuilder($ouvrage)->getQuery()->getResult();
    }

    public function getByOuvrage(Ouvrage $ouvrage = null, $offset=Config::DEFAULT_OFFSET_PAGINATOR, $page=1)
    {
        return Pagination::renderPagination($this->getByOuvrageBuilder($ouvrage)->getQuery(), $offset, $page);
    }

    public function getByOuvrageBuilder(Ouvrage $ouvrage = null)
    {
        $qb = $this->createDefaultBuilder();
        $qb->where($qb->expr()->eq('o', ':ouvrage'))
            ->setParameter('ouvrage', $ouvrage)
        ;
        $qb = $this->myDefaultOrder($qb);
        return $qb;
    }

    public function getAll($offset=Config::DEFAULT_OFFSET_PAGINATOR, $page = 1)
    {
        return Pagination::renderPagination($this->getAllQuery(), $offset, $page);
    }

    public  function getAllQuery()
    {
        $qb = $this->createDefaultBuilder();
        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    public function getFullByCriteres(array $criteres=array())
    {
        return $this->getCritereQuery($criteres)->getResult();
    }

    public function getByCriteres(array $criteres=array(), $offset=Config::DEFAULT_OFFSET_PAGINATOR, $page=1)
    {
        return Pagination::renderPagination($this->getCritereQuery($criteres), $offset, $page);
    }

    public function getCritereQuery(array $criteres = array())
    {
        $qb = $this->createDefaultBuilder();

        // Critère ouvrage
        if(!empty($criteres['ouvrage'])){
            $qb = $this->critereOuvrage($qb, $criteres['ouvrage']);
        }
        // Critère dateApp
        if(!empty($criteres['dateApp'])){
            $qb = $this->critereDateApparution($qb, $criteres['dateApp']);
        }
        // Critère dateDebutRep
        if(!empty($criteres['dateDebutRep'])){
            $qb = $this->critereDateDebutRep($qb, $criteres['dateDebutRep']);
        }
        // Critère datePriseCharge
        if(!empty($criteres['datePriseCharge'])){
            $qb = $this->critereDatePriseCharge($qb, $criteres['datePriseCharge']);
        }
        // Critère dateReparation
        if(!empty($criteres['dateReparation'])){
            $qb = $this->critereDateReparation($qb, $criteres['dateReparation']);
        }
        // Critère typePanne
        if(!empty($criteres['typePanne'])){
            $qb = $this->critereTypePanne($qb, $criteres['typePanne']);
        }
        // Critère numéro
        if(array_key_exists('numero', $criteres) && $criteres['numero'] != ''){
            $qb = $this->critereNumero($qb, $criteres['numero']);
        }

        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    protected function critereOuvrage(QueryBuilder $qb, Ouvrage $ouvrage = null)
    {
        if(!empty($ouvrage)){
            $qb->andWhere($qb->expr()->eq('p.ouvrage', ':ouvrage'))->setParameter('ouvrage', $ouvrage);
        }
        return $qb;
    }

    protected function critereDateApparution(QueryBuilder $qb, array $dateApp = array())
    {
        if(!empty($dateApp)){
            if(empty($dateApp['start'])) $dateApp['start'] = new \DateTime('now');
            if(empty($dateApp['end'])) $dateApp['end'] = new \DateTime('now');
            $qb->andWhere($qb->expr()->between('p.dateApparution', ':start', ':end'))
                ->setParameter('start', $dateApp['start'])
                ->setParameter('end', $dateApp['end'])
            ;
        }
        return $qb;
    }

    protected function critereDatePriseCharge(QueryBuilder $qb, array $datePriseCharge = array())
    {
        if(!empty($datePriseCharge)){
            if(empty($datePriseCharge['start'])) $datePriseCharge['start'] = new \DateTime('now');
            if(empty($datePriseCharge['end'])) $datePriseCharge['end'] = new \DateTime('now');
            $qb->andWhere($qb->expr()->between('p.datePriseCharge', ':start', ':end'))
                ->setParameter('start', $datePriseCharge['start'])
                ->setParameter('end', $datePriseCharge['end'])
            ;
        }
        return $qb;
    }

    protected function critereDateDebutRep(QueryBuilder $qb, array $dateDebutRep = array())
    {
        if(!empty($dateDebutRep)){
            if(empty($dateDebutRep['start'])) $dateDebutRep['start'] = new \DateTime('now');
            if(empty($dateDebutRep['end'])) $dateDebutRep['end'] = new \DateTime('now');
            $qb->andWhere($qb->expr()->between('p.dateDebutRep', ':start', ':end'))
                ->setParameter('start', $dateDebutRep['start'])
                ->setParameter('end', $dateDebutRep['end'])
            ;
        }
        return $qb;
    }
    
    protected function critereDateReparation(QueryBuilder $qb, array $dateReparation = array())
    {
        if(!empty($dateReparation)){
            if(empty($dateReparation['start'])) $dateReparation['start'] = new \DateTime('now');
            if(empty($dateReparation['end'])) $dateReparation['end'] = new \DateTime('now');
            $qb->andWhere($qb->expr()->between('p.dateReparation', ':start', ':end'))
                ->setParameter('start', $dateReparation['start'])
                ->setParameter('end', $dateReparation['end'])
            ;
        }
        return $qb;
    }

    protected function critereTypePanne(QueryBuilder $qb, TypePanne $typePanne = null)
    {
        if(!is_null($typePanne)){
            $qb->andWhere($qb->expr()->eq('t', ':typePanne'))->setParameter('typePanne', $typePanne);
        }
        return $qb;
    }

    protected function critereNumero(QueryBuilder $qb, $numero)
    {
        if($numero != ''){
            $qb->andWhere($qb->expr()->like('p.numero', $qb->expr()->literal($numero.'%')));
        }
        return $qb;
    }

    protected function createDefaultBuilder()
    {
        $qb = $this->createQueryBuilder('p');
        $qb = $this->myDefaultSelectAll($qb);
        return $qb;
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb->leftJoin('p.ouvrage', 'o')
                ->addSelect('o')
            ->leftJoin('p.statutPanne', 's')
                ->addSelect('s')
            ->leftJoin('p.typePanne', 't')
                ->addSelect('t')
            ->leftJoin('p.appels', 'a')
                ->addSelect('a')
            ->leftJoin('p.notifications', 'n')
                ->addSelect('n')
        ;

        return $qb;
    }

    protected function myDefaultOrder(QueryBuilder $qb)
    {
        $qb->orderBy('p.id', 'DESC');

        return $qb;
    }

    protected function defaultUserFilter(QueryBuilder $qb, User $user = null)
    {
        if($user && $user->isLoadRegional()){
            $qb->leftJoin('o.localite', 'l')
                ->andWhere($qb->expr()->eq('l.region', ':region'))
                ->setParameter('region', $user->getRegion())
            ;
        }
        return $qb;
    }

    protected function myDefaultFilter(QueryBuilder $qb)
    {
        $site = ParameterFile::loadSite();
        if(!is_null($site)) {
            $qb->leftJoin('o.localite', 'l')
                ->leftJoin('l.region', 'r')
                ->andWhere($qb->expr()->eq('r.id', ':region'))
                ->setParameter('region', $site);
        }
        return $qb;
    }
}
