<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
    public function get($id)
    {
        $qb = $this->createDefaultBuilder();
        $qb->andWhere($qb->expr()->eq('p.id', ':id'))->setParameter('id', intval($id));
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getByMustInitializedBuilder()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where($qb->expr()->in('p.id', ':mustInitialized'))
            ->setParameter('mustInitialized', Profile::getMustInitializedArray())
        ;
        return $qb;
    }

    public function getAgentsProfileBuider()
    {
        $qb = $this->createQueryBuilder('p');
        return $qb->where($qb->expr()->in('p.id', array(3,4,5)))->orderBy('p.designation');
    }

    public function getForUserActionBuilder()
    {
        $qb = $this->createQueryBuilder('p');
        //return $qb->where($qb->expr()->in('p.id', Profile::getForUserActionArray()))->orderBy('p.designation');
		return $qb->where($qb->expr()->notIn('p.id', array(Profile::PROFILE_REPARATEUR, Profile::PROFILE_COMITE)))->orderBy('p.designation');
		//return $qb->orderBy('p.designation');
    }

    public function getForAdminActionBuilder()
    {
        $qb = $this->createQueryBuilder('p');
        //return $qb->where($qb->expr()->in('p.id', Profile::getForAdminActionArray()))->orderBy('p.designation');
		return $qb->where($qb->expr()->notIn('p.id', array(Profile::PROFILE_REPARATEUR, Profile::PROFILE_COMITE)))->orderBy('p.designation');
		//return $qb->orderBy('p.designation');
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb->leftJoin('p.numeroAppels', 'n')
                ->addSelect('n')
            ->leftJoin('p.agents', 'a')
                ->addSelect('a')
            ->leftJoin('p.codes', 'c')
                ->addSelect('c')
        ;

        return $qb;
    }

    protected function createDefaultBuilder()
    {
        $qb = $this->createQueryBuilder('p');
        $qb = $this->myDefaultSelectAll($qb);
        return $qb;
    }

    protected function myDefaultOrder(QueryBuilder $qb)
    {
        $qb->orderBy('p.id', 'DESC');

        return $qb;
    }
}
