<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Sofie\AdminBundle\Entity\Config;
use Sofie\AdminBundle\Model\ParameterFile;
use Sofie\UserBundle\Entity\User;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository
{
    public function get($id)
    {
        $qb = $this->createDefaultBuilder();
        $qb->andWhere($qb->expr()->eq('r.id', ':id'))->setParameter('id', intval($id));
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getFullAll()
    {
        return $this->getAllQuery()->getResult();
    }

    public function getAll($offset=Config::DEFAULT_OFFSET_PAGINATOR, $page = 1)
    {
//        return Pagination::renderPagination($this->getAllQuery(), $offset, $page);
        return $this->getAllQuery()->getResult();
    }

    public function getAllQuery()
    {
        $qb = $this->createDefaultBuilder();
        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    public function getByUserRegionBuilder()
    {
        $qb = $this->createQueryBuilder('r');
        return $this->myDefaultFilter($qb);
    }

    public function getByUserRegion()
    {
        return $this->getByUserRegionBuilder()->getQuery()->getResult();
    }

    public function getOneByUserRegion()
    {
        try{
            return $this->getByUserRegionBuilder()->getQuery()->getOneOrNullResult();
        }catch (NonUniqueResultException $e){
            return null;
        }

    }

    public function getNextId()
    {
        return intval($this->createQueryBuilder('r')->select('MAX(r.id)')->getQuery()->getSingleScalarResult())+1;
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb
            ->leftJoin('r.localites', 'l')
                ->addSelect('l')
            ->leftJoin('l.reparateur', 're')
                ->addSelect('re')
            ->leftJoin('r.agents', 'a')
                ->addSelect('a')
            ->leftJoin('r.iddr', 'iddr')
                ->addSelect('iddr')
            ->leftJoin('r.sociologue', 's')
                ->addSelect('s')
            ->leftJoin('r.config', 'c')
                ->addSelect('c')
        ;

        return $qb;
    }

    protected function createDefaultBuilder()
    {
        $qb = $this->createQueryBuilder('r');
        $qb = $this->myDefaultSelectAll($qb);
        $qb = $this->myDefaultFilter($qb);
        return $qb;
    }

    protected function myDefaultOrder(QueryBuilder $qb)
    {
        $qb->orderBy('r.nom', 'ASC')
            ->addOrderBy('r.id', 'DESC')
        ;

        return $qb;
    }

    protected function defaultUserFilter(QueryBuilder $qb, User $user = null)
    {
        /*if($user && $user->isLoadRegional()){
            $qb->andWhere($qb->expr()->eq('r', ':region'))
                ->setParameter('region', $user->getRegion())
            ;
        }*/
        return $qb;
    }

    protected function myDefaultFilter(QueryBuilder $qb)
    {
        $site = ParameterFile::loadSite();
        if(!is_null($site)){
            $qb->andWhere($qb->expr()->eq('r.id', ':region'))
                ->setParameter('region', $site)
            ;
        }
        return $qb;
    }
}
