<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Sofie\AdminBundle\Entity\Config;
use Sofie\AdminBundle\Model\ParameterFile;
use Sofie\UserBundle\Entity\User;

/**
 * ReparateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReparateurRepository extends EntityRepository
{
    public function getNextId()
    {
        return intval($this->createQueryBuilder('r')->select('MAX(r.id)')->getQuery()->getSingleScalarResult())+1;
    }

    public function get($id)
    {
        $qb = $this->createDefaultBuilder();
        $qb->andWhere($qb->expr()->eq('r.id', ':id'))->setParameter('id', intval($id));
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getTotalAll()
    {
        return $this->getAllQuery()->getResult();
    }

    public function getAll($offset=Config::DEFAULT_OFFSET_PAGINATOR, $page = 1)
    {
        return Pagination::renderPagination($this->getAllQuery(), $offset, $page);
    }

    public  function getAllQuery()
    {
        $qb = $this->createDefaultBuilder();
        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    public function getTotalByCriteres(array $criteres=array())
    {
        return $this->getCritereQuery($criteres)->getResult();
    }

    public function getByCriteres(array $criteres=array(), $offset=Config::DEFAULT_OFFSET_PAGINATOR, $page=1)
    {
        return Pagination::renderPagination($this->getCritereQuery($criteres), $offset, $page);
    }

    public function getCritereQuery(array $criteres = array())
    {
        $qb = $this->createDefaultBuilder();

        // Critère région
        if(array_key_exists('region', $criteres)){
            $qb = $this->critereRegion($qb, $criteres['region']);
        }

        // Critère codeInit
        if(array_key_exists('codeInit', $criteres) && $criteres['codeInit'] != ''){
            $qb = $this->critereCodeInit($qb, $criteres['codeInit']);
        }
        // Critère numeroAppel
        if(array_key_exists('numeroAppel', $criteres) && $criteres['numeroAppel'] != ''){
            $qb = $this->critereNumeroAppel($qb, $criteres['numeroAppel']);
        }
        // Critère nom
        if(array_key_exists('nom', $criteres) && $criteres['nom'] != ''){
            $qb = $this->critereNom($qb, $criteres['nom']);
        }
        // Critère prenoms
        if(array_key_exists('prenoms', $criteres) && $criteres['prenoms'] != ''){
            $qb = $this->criterePrenoms($qb, $criteres['prenoms']);
        }
        // Critère initStatus
        if(array_key_exists('initStatus', $criteres) && $criteres['initStatus'] != ''){
            $qb = $this->critereInitStatus($qb, $criteres['initStatus']);
        }

        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    protected function critereRegion(QueryBuilder $qb, Region $region = null)
    {
        if(!empty($region)){
            $qb->andWhere($qb->expr()->eq('l.region', ':region'))->setParameter('region', $region);
        }
        return $qb;
    }

    protected function critereCodeInit(QueryBuilder $qb, $codeInit)
    {
        if($codeInit != ''){
            $qb->andWhere($qb->expr()->like('r.codeInit', $qb->expr()->literal($codeInit.'%')));
        }
        return $qb;
    }

    protected function critereNumeroAppel(QueryBuilder $qb, $numeroAppel)
    {
        if($numeroAppel != ''){
            $qb->andWhere($qb->expr()->like('n.numero', $qb->expr()->literal($numeroAppel.'%')));
        }
        return $qb;
    }

    protected function critereNom(QueryBuilder $qb, $nom)
    {
        if($nom != ''){
            $qb->andWhere($qb->expr()->like('r.nom', $qb->expr()->literal($nom.'%')));
        }
        return $qb;
    }

    protected function criterePrenoms(QueryBuilder $qb, $prenoms)
    {
        if($prenoms != ''){
            $qb->andWhere($qb->expr()->like('r.prenoms', $qb->expr()->literal($prenoms.'%')));
        }
        return $qb;
    }

    protected function critereInitStatus(QueryBuilder $qb, $initStatus = null)
    {
        if(!is_null($initStatus) && $initStatus != ''){
            if($initStatus==0){
                $qb->andWhere(
                    $qb->expr()->orX(
                        $qb->expr()->eq('r.initStatus', ':initStatus'),
                        $qb->expr()->isNull('r.initStatus')
                    )
                )
                    ->setParameter('initStatus', intval($initStatus))
                ;
            }else{
                $qb->andWhere($qb->expr()->eq('r.initStatus', ':initStatus'))->setParameter('initStatus', intval($initStatus));
            }

        }
        return $qb;
    }

    public function getByRegionsIn(array $list)
    {
        $qb = $this->createQueryBuilder('r')
            ->leftJoin('r.localites', 'l')
            ->leftJoin('l.region', 're')
        ;
        $qb->where($qb->expr()->in('re.id', $list));

        return $qb->getQuery()->getResult();
    }

    public function getByLocalitesIn(array $list)
    {
        $qb = $this->createQueryBuilder('r')
            ->innerJoin('r.localites', 'l')
        ;
        $qb->where($qb->expr()->in('l.id', ':list'))->setParameter('list', $list);

        return $qb->getQuery()->getResult();
    }

    public function getByRegionBuilder(Region $region = null)
    {
        $qb = $this->createQueryBuilder('r')
            ->leftJoin('r.localites', 'l')
        ;
        $qb->where($qb->expr()->eq('l.region', ':region'))
            ->setParameter('region', $region)
        ;
        return $qb;
    }

    public function getByUserRegionBuilder()
    {
        $qb = $this->createQueryBuilder('r')
            ->leftJoin('r.localites', 'l')
        ;
        return $qb;
    }

    public function getByUserRegion()
    {
        return $this->getByUserRegionBuilder()->getQuery()->getResult();
    }

    protected function createDefaultBuilder()
    {
        $qb = $this->createQueryBuilder('r');
        $qb = $this->myDefaultSelectAll($qb);
        return $qb;
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb->leftJoin('r.localites', 'l')
            ->addSelect('l')
            ->leftJoin('r.numeroAppel', 'n')
            ->addSelect('n')
        ;

        return $qb;
    }

    protected function myDefaultOrder(QueryBuilder $qb)
    {
        $qb->orderBy('r.createdAt', 'DESC')
            ->addOrderBy('r.nom', 'ASC')
            ->addOrderBy('r.prenoms', 'ASC')
            ->addOrderBy('r.id', 'DESC')
        ;

        return $qb;
    }

    protected function defaultUserFilter(QueryBuilder $qb, User $user = null)
    {
        /*if($user && $user->isLoadRegional()){
            $qb->andWhere($qb->expr()->eq('l.region', ':region'))
                ->setParameter('region', $user->getRegion())
            ;
        }*/
        return $qb;
    }

    protected function myDefaultFilter(QueryBuilder $qb)
    {
        $site = ParameterFile::loadSite();
        if(!is_null($site) && intval($site)>0){
            $qb->andWhere($qb->expr()->eq('l.region', ':region'))
                ->setParameter('region', $site)
            ;
        }
        return $qb;
    }
}
