<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SuiviPhysicoChimiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviPhysicoChimiqueRepository extends EntityRepository
{
    public function insert(SuiviPhysicoChimique $suiviPhysicoChimique, array $data)
    {
        $con = $this->getEntityManager()->getConnection();

        if($suiviPhysicoChimique->getId() != null){
            $data['IDSuiviphysicochimique'] = $suiviPhysicoChimique->getId();
        }
        if(isset($data['Date'])){
            unset($data['Date']);
            $data['`Date`'] = $suiviPhysicoChimique->getDate()->format('Y-m-d');
        }
        if(isset($data['As'])){
            unset($data['As']);
            $data['`As`'] = $suiviPhysicoChimique->getAs();
        }
        if(isset($data['position'])){
            unset($data['position']);
        }
        if($suiviPhysicoChimique->getOuvrage()){
            $data['IDOuvrage'] = $suiviPhysicoChimique->getOuvrage()->getId();
        }
        $con->insert('t_suiviphysicochimique', $data);
    }

    public function getNextId()
    {
        return intval($this->createQueryBuilder('s')->select('MAX(s.id)')->getQuery()->getSingleScalarResult())+1;
    }
}
