<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Sofie\AdminBundle\Entity\Config;

/**
 * TypePanneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePanneRepository extends EntityRepository
{
    public function getNextId()
    {
        return intval($this->createQueryBuilder('t')->select('MAX(t.id)')->getQuery()->getSingleScalarResult())+1;
    }

    public function get($id)
    {
        $qb = $this->createDefaultBuilder();
        $qb->andWhere($qb->expr()->eq('t.id', ':id'))->setParameter('id', intval($id));
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getFullAll()
    {
        return $this->getAllQuery()->getResult();
    }

    public function getAll($offset=Config::DEFAULT_OFFSET_PAGINATOR, $page=1)
    {
        return Pagination::renderPagination($this->getAllQuery(), $offset, $page);
    }

    public  function getAllQuery()
    {
        $qb = $this->createDefaultBuilder();
        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    public function getTotalByCriteres(array $criteres=array())
    {
        return $this->getCritereQuery($criteres)->getResult();
    }

    public function getByCriteres(array $criteres=array(), $offset=Config::DEFAULT_OFFSET_PAGINATOR, $page=1)
    {
        return Pagination::renderPagination($this->getCritereQuery($criteres), $offset, $page);
    }

    public function getCritereQuery(array $criteres = array())
    {
        $qb = $this->createDefaultBuilder();

        // Critère libelle
        if(array_key_exists('libelle', $criteres) && $criteres['libelle'] != ''){
            $qb = $this->critereLibelle($qb, $criteres['libelle']);
        }

        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    protected function critereLibelle(QueryBuilder $qb, $libelle)
    {
        if($libelle != ''){
            $qb->andWhere($qb->expr()->like('t.libelle', $qb->expr()->literal($libelle.'%')));
        }
        return $qb;
    }

    public function createDefaultBuilder()
    {
        $qb = $this->createQueryBuilder('t');
        $qb = $this->myDefaultSelectAll($qb);
        return $qb;
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb->leftJoin('t.pannes', 'p')
            ->addSelect('p')
        ;

        return $qb;
    }

    protected function myDefaultOrder(QueryBuilder $qb)
    {
        $qb->orderBy('t.id', 'DESC');

        return $qb;
    }
}
