<?php

namespace Sofie\ExpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VenuEauPrincipaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VenuEauPrincipaleRepository extends EntityRepository
{
    public function getNextId()
    {
        return intval($this->createQueryBuilder('c')->select('MAX(c.id)')->getQuery()->getSingleScalarResult())+1;
    }
}
