<?php

namespace Sofie\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DroitCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DroitCategoryRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->getAllQuery()->getQuery()->getResult();
    }

    public function getAllQuery()
    {
        $qb = $this->createQueryBuilder('dc');
        $qb->leftJoin('dc.droits', 'd')
            ->addSelect('d')
            ->orderBy('dc.libelle', 'ASC')
            ->addOrderBy('d.libelle', 'ASC')
        ;
        return $qb;
    }
}
