<?php

namespace Sofie\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * DroitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DroitRepository extends EntityRepository
{
    public function getAllArray()
    {
        return $this->createQueryBuilder('d')->getQuery()->getArrayResult();
    }

    public function get($id)
    {
        $qb = $this->createDefaultBuilder();
        $qb->andWhere($qb->expr()->eq('d.id', ':id'))->setParameter('id', intval($id));
        return $qb->getQuery()->getOneOrNullResult();
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb->leftJoin('d.droitCategory', 'dc')
                ->addSelect('dc')
            ->leftJoin('d.groupeDroits', 'gd')
                ->addSelect('gd')
            ->leftJoin('gd.groupe', 'g')
                ->addSelect('g')
            ->leftJoin('g.userGroupes', 'ug')
                ->addSelect('ug')
            ->leftJoin('ug.user', 'u')
                ->addSelect('u')
        ;

        return $qb;
    }

    protected function createDefaultBuilder()
    {
        $qb = $this->createQueryBuilder('d');
        $qb = $this->myDefaultSelectAll($qb);
        return $qb;
    }

    protected function myDefaultOrder(QueryBuilder $qb)
    {
        $qb->orderBy('dc.libelle', 'ASC')
            ->addOrderBy('d.libelle', 'ASC')
            ->addOrderBy('d.id', 'DESC')
        ;

        return $qb;
    }
}
