<?php

namespace Sofie\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Sofie\AdminBundle\Entity\Config;
use Sofie\ExpBundle\Entity\Pagination;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends EntityRepository
{
    public function getNextId()
    {
        return intval($this->createQueryBuilder('g')->select('MAX(g.id)')->getQuery()->getSingleScalarResult())+1;
    }

    public function getFullAll()
    {
        return $this->getAllQuery()->getResult();
    }

    public function get($id)
    {
        $qb = $this->createDefaultBuilder();
        $qb->andWhere($qb->expr()->eq('g.id', ':id'))
            ->setParameter('id', intval($id))
        ;
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getAll($offset=Config::DEFAULT_OFFSET_PAGINATOR, $page = 1)
    {
        return Pagination::renderPagination($this->getAllQuery(), $offset, $page);
    }

    public  function getAllQuery()
    {
        $qb = $this->createDefaultBuilder();
        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    public function getFullByCriteres(array $criteres=array())
    {
        return $this->getCritereQuery($criteres)->getResult();
    }

    public function getByCriteres(array $criteres=array(), $offset=Config::DEFAULT_OFFSET_PAGINATOR, $page=1)
    {
        return Pagination::renderPagination($this->getCritereQuery($criteres), $offset, $page);
    }

    public function getCritereQuery(array $criteres = array())
    {
        $qb = $this->createDefaultBuilder();

        // Critère nom
        if(array_key_exists('nom', $criteres) && $criteres['nom'] != ''){
            $qb = $this->critereNom($qb, $criteres['nom']);
        }

        $qb = $this->myDefaultOrder($qb);
        return $qb->getQuery();
    }

    protected function critereNom(QueryBuilder $qb, $nom)
    {
        if($nom != ''){
            $qb->andWhere($qb->expr()->like('g.name', $qb->expr()->literal($nom.'%')));
        }
        return $qb;
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb->leftJoin('g.userGroupes', 'ug')
                ->addSelect('ug')
            ->leftJoin('ug.user', 'u')
                ->addSelect('u')
            ->leftJoin('g.groupeDroits', 'gd')
                ->addSelect('gd')
            ->leftJoin('gd.droit', 'd')
                ->addSelect('d')
        ;

        return $qb;
    }

    protected function createDefaultBuilder()
    {
        $qb = $this->createQueryBuilder('g');
        $qb = $this->myDefaultSelectAll($qb);
        return $qb;
    }

    protected function myDefaultOrder(QueryBuilder $qb)
    {
        $qb->orderBy('g.name', 'DESC')
            ->addOrderBy('g.id', 'DESC')
        ;
        return $qb;
    }
}
