<?php

namespace Sofie\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupeDroitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeDroitRepository extends EntityRepository
{
    public function get($groupeId, $droitId)
    {
        $qb = $this->createQueryBuilder('gd');
        $qb->innerJoin('gd.groupe', 'g')
        ->innerJoin('gd.droit', 'd')
        ->where(
            $qb->expr()->andX(
                $qb->expr()->eq('g.id', ':groupe'),
                $qb->expr()->eq('d.id', ':droit')
            )
        )
            ->setParameter('groupe', $groupeId)
            ->setParameter('droit', $droitId)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }
}
