<?php

namespace Sofie\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * UserGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupeRepository extends EntityRepository
{
    public function get(User $user = null, Groupe $groupe = null)
    {
        if(is_null($user) || is_null($groupe)){
            return null;
        }
        if(is_null($user->getId()) || is_null($groupe->getId())){
            return null;
        }
        $qb = $this->createDefaultBuilder();
        $qb->where(
            $qb->expr()->andX(
                $qb->expr()->eq('u.id', ':user'),
                $qb->expr()->eq('g.id', ':groupe')
            )
        )
            ->setParameter('user', $user->getId())
            ->setParameter('groupe', $groupe->getId())
        ;
        return $qb->getQuery()->getOneOrNullResult();
    }

    protected function myDefaultSelectAll(QueryBuilder $qb)
    {
        $qb
            ->leftJoin('ug.groupe', 'g')
            ->addSelect('g')
            ->leftJoin('ug.user', 'u')
            ->addSelect('u')
        ;

        return $qb;
    }

    protected function createDefaultBuilder()
    {
        $qb = $this->createQueryBuilder('ug');
        $qb = $this->myDefaultSelectAll($qb);
        return $qb;
    }
}
